---
title: "File Downloads"
author: "Dominique Paul"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# About

This script just serves to download all relevant files for the analysis to ease reproducibility All data can also be found at the Encode entries listed here:

* RNA: https://www.encodeproject.org/treatment-time-series/ENCSR897XFT/
* GR ChIP: https://www.encodeproject.org/treatment-time-series/ENCSR210PYP/
* JUNB ChIP: https://www.encodeproject.org/treatment-time-series/ENCSR483SDK/
* ATAC: https://www.encodeproject.org/treatment-time-series/ENCSR385LRX/

# Download RNA data

```{r, eval=FALSE}
# ENCODE4 v1.2.3 GRCh38 V29 (ENCAN887WHM) processed data

# Control
# https://www.encodeproject.org/experiments/ENCSR632DQP/
download.file("https://www.encodeproject.org/files/ENCFF285BTU/@@download/ENCFF285BTU.tsv", "../data/reddy_rna_control_r1.tsv")
download.file("https://www.encodeproject.org/files/ENCFF904PCS/@@download/ENCFF904PCS.tsv", "../data/reddy_rna_control_r2.tsv")
download.file("https://www.encodeproject.org/files/ENCFF360GXF/@@download/ENCFF360GXF.tsv", "../data/reddy_rna_control_r3.tsv")
download.file("https://www.encodeproject.org/files/ENCFF233CZT/@@download/ENCFF233CZT.tsv", "../data/reddy_rna_control_r4.tsv")

# 12h DEX treatment
# https://www.encodeproject.org/experiments/ENCSR154TDP
download.file("https://www.encodeproject.org/files/ENCFF864UKR/@@download/ENCFF864UKR.tsv", "../data/reddy_rna_DEX12h_r1.tsv")
download.file("https://www.encodeproject.org/files/ENCFF928EKJ/@@download/ENCFF928EKJ.tsv", "../data/reddy_rna_DEX12h_r2.tsv")
download.file("https://www.encodeproject.org/files/ENCFF988JYH/@@download/ENCFF988JYH.tsv", "../data/reddy_rna_DEX12h_r3.tsv")
download.file("https://www.encodeproject.org/files/ENCFF248HYY/@@download/ENCFF248HYY.tsv", "../data/reddy_rna_DEX12h_r4.tsv")
```

# Download bed and bigwig files for the GC receptor

```{r, eval=FALSE}
# Bed file for after 12h treatment
download.file("https://www.encodeproject.org/files/ENCFF567KLR/@@download/ENCFF567KLR.bed.gz", "../data/reddy_bed_DEX12h_r123.bed.gz")
R.utils::gunzip("../data/reddy_bed_DEX12h_r123.bed.gz")

# BigWig file
download.file("https://www.encodeproject.org/files/ENCFF638NRS/@@download/ENCFF638NRS.bigWig", "../data/reddy_bigwig_DEX12h_r123.bigWig")

# Bed file for 2h DEX treatment
download.file("https://www.encodeproject.org/files/ENCFF869DAZ/@@download/ENCFF869DAZ.bed.gz", "../data/reddy_bed_DEX2h_r123.bed.gz")

# Bigwig for 2h DEX  treatment
download.file("https://www.encodeproject.org/files/ENCFF910SEI/@@download/ENCFF910SEI.bigWig", "../data/reddy_bigwig_DEX2h_r123.bigWig")
```

# Download bed files for JUNB

```{r, eval=FALSE}
# Bed file for 12h treatment
download.file("https://www.encodeproject.org/files/ENCFF278BHW/@@download/ENCFF278BHW.bed.gz", "../data/reddy_bed_JUNB_DEX12h_r123.bed.gz")
R.utils::gunzip("../data/reddy_bed_JUNB_DEX12h_r123.bed.gz")

# BigWig file
download.file("https://www.encodeproject.org/files/ENCFF091VQD/@@download/ENCFF091VQD.bigWig", "../data/reddy_bigwig_JUNB_DEX12h_r123.bigWig")
```

# Download ATAC-seq data

```{r, eval=FALSE}
download.file("https://www.encodeproject.org/files/ENCFF735UWS/@@download/ENCFF735UWS.bed.gz",
              "../data/reddy_bed_ATAC_control.bed.gz")
download.file("https://www.encodeproject.org/files/ENCFF139XJH/@@download/ENCFF139XJH.bed.gz",
              "../data/reddy_bed_ATAC_12h_DEX.bed.gz")

```



